version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smartshort-mongodb-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-smartshort}
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - smartshort-network-dev
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Server (Development)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: smartshort-backend-dev
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-smartshort}?authSource=admin
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - smartshort-network-dev

  # Frontend Application (Development)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: smartshort-frontend-dev
    restart: unless-stopped
    env_file:
      - ./client/.env.local
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - smartshort-network-dev

volumes:
  mongodb_data_dev:
    driver: local

networks:
  smartshort-network-dev:
    driver: bridge 